export const Colors = {
    primary: "#3364ff",
    warning: "#8c8c8c",

    dark: {
        text: "#fcfbfd",
        title: "#fff",
        background: "#131150",
        navBackground: "#302f82",
        iconColor: "#9591a5",
        iconColorFocused: "#fff",
        iconBackground: "#a9b0ba",
        uiBackground: "#e1e6ed",
        cardBackground: "#b5bdc9",
        cardBorder: "#E9F0FE",
        alertBackground: "#131150",
        tint: '#3364ff',
        buttonText: "#f2f2f2",
        statusbarBackground: '#302f82',
        warning: "#fffc",
    },

    light: {
        text: "#112954",
        title: "#201e2b",
        background: "#f5f8fc",
        navBackground: "#fff",
        iconColor:"#888a94",
        iconColorFocused: "#3364ff",
        iconBackground: "#c2d0ff",
        uiBackground: "#e1e6ed",
        cardBackground: "#5289F6",
        cardBorder: "#c8caceff",
        alertBackground: "#fff",
        tint: '#c2d0ff',
        buttonText: "#f2f2f2",
        statusbarBackground: '#d8d8d8ff',
        warning: "#8c8c8c",
    },

}